### ISSUE TITLE
Input type tel

### ISSUE THREAD

**Issue by scott-w** [adamcupial/django-html5-forms#6]
We need an Html5TelField which should render an input with type tel.

**Comment by adamcupial** [comment]
Just fork and then pull request, it's a 3 line change:

in widgets.py add

``` python
class Html5TelInput(Html5TextInput):
    input_type = 'tel'
```

in fields.py add

``` python
class Html5TelField(Html5CharField):
    """ Tel field

    apart from default widget works just like CharField
    """
    widget = Html5TelInput
```

And add yourself to readme, and of course also document new field type there.

Since phone numbers are heavily locale specific I'd leave off validation, There're some phone number validators in django.contrib.localflavor (or since 1.5 django_localflavor) but they're locale specific. 
Only generic phone validator I know of is https://pypi.python.org/pypi/phonenumbers, but it would mean adding dependencies to django-html5.

If this issue is open by the end of week, I probably can do it myself.

**Comment by scott-w** [comment]
Hi, yeah that was my intent. I have a habit of creating tickets for everything I do.

The validation was to ensure it is all digits, with extra things like spaces, pluses, dashes and parentheses allowed. Nothing too special, to be honest. I must admit to not knowing a lot about phone numbers, though.

**Comment by adamcupial-codepill** [comment]
In that case just add your own validator (regex), propose to create validators.py

**Comment by adamcupial** [comment]
Sorry It took so long, Change of github interface has an unforseen effect on me - I don't see pull requests. Merged && working, along with my addition of Html5ChoiceField
